### ISSUE TITLE
Liven up the README

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/dharma_quotes#4]
The readme looks a bit modest doesn't it! Can someone liven it up with colourful emojis and banterous puns?

**Comment by BatoolMM** [comment]
Can I give it a try, please? I am quite a newbie to programming and this is the first time I am trying to contribute to an open-source project. Can I do this for Hacktoberfest, please?

**Comment by BatoolMM** [comment]
Hi @Evie-Skinner18 , Can you assign it to me, please?

**Comment by Evie-Skinner18** [comment]
Hi! I want lots of people to get involved so going to avoid assigning to an individual. Just go for it! 😄
